name: Build/Release

on:
  push:
    branches: [ master ]

jobs:
  windows:
    runs-on: windows-2019

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Initialize Environment
        uses: actions/setup-node@v3
        with:
          node-version: 18.18.1

      - name: Install Dependencies
        run: yarn
      
      - name: Build and Upload Release
        run: yarn release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

  linux:
   runs-on: ubuntu-22.04

   steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Initialize Environment
        uses: actions/setup-node@v3
        with:
          node-version: 18.18.1

      - name: Install Dependencies
        run: yarn

      - name: Build and Upload Release
        run: yarn release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}